title: Hello World
theme: minima
author: BruceChen2017
github_username: BruceChen2017
description: Personal Blogs
show_excerpts: true
google_analytics: G-WKPJDTL57E
plugins:
- jekyll-feed

exclude: [vendor, others, codes]
